### ISSUE TITLE
Model has more than one child

### ISSUE THREAD

**Issue by masterchen** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#1]
What shold i do if one master model has more than one child ? thanks

**Comment by masterchen** [comment]
And  what's the raltion between Master and child

**Comment by 7matrook7** [comment]
Dear sir, I have not work before with coderush. Sir Can I know about you how the database work in this project and **where is located the data base.** and oblige there bye....

yours obediently
"shuvo"

**Comment by panxor19** [comment]
Hello, I have a question, how to get the query from the database?

**Comment by panxor19** [comment]
Do you have to pay to have the database?

**Comment by masterchen** [comment]
thanks go2ismail!  no need to pay , the project worked with “entityframework “, if you dont know what is ef ,you get get help from google

**Comment by 7matrook7** [comment]
OK sir

**Comment by go2ismail** [comment]
the database will be automatically created. just make sure to have correct connection string at appsettings.json
![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/90965900-034a-4450-b2ad-bb04bc2bb3a9)
