### ISSUE TITLE
double unit Price

### ISSUE THREAD

**Issue by ozzyozg** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#10]
first of all appreciate your efforts
I want to insert unit price as double but it is not possible...
what am i doing wrong?
thanks

**Comment by LeeWheeler** [comment]
change the model and migrate

**Comment by go2ismail** [comment]
the newer version already used double for the unit price
![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/4f2f8e95-b9fc-4e56-b320-c0cb942dbc2e)
