### ISSUE TITLE
The message prompt that you don't have access to this resource after you change admin 

### ISSUE THREAD

**Issue by prince19999** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#13]
Please help me

**Comment by LeeWheeler** [comment]
Buy the original

**Comment by go2ismail** [comment]
please try the newer version: https://whms-lte.csharpasp.net/Dashboards/DefaultDashboard

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/c887fbc6-4f6b-4923-bee1-6b06af5417fa)
