### ISSUE TITLE
How to deploy this project in IIS?

### ISSUE THREAD

**Issue by deepakkumpala** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#18]
How to deploy this project in IIS?

**Comment by LeeWheeler** [comment]
Create a publishing profile - (youtube) and then publish it.

**Comment by go2ismail** [comment]
README file already added information how to run the project locally and IIS deployment

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/80ac09b5-8865-45a1-9645-a10b007e1d36)
