### ISSUE TITLE
Hi! Please tell me how to run and deploy this project on MAC. I've tried so many solutions but still unable to run it on MAC. I need this project for inventory system. It would be a great help

### ISSUE THREAD

**Issue by hamzabukharicloudpacer** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#19]

**Comment by simphonydeveloper** [comment]
This respository has not been updated for many years.

**Comment by LeeWheeler** [comment]
It was updated 3 weeks ago, and for the OP you need visual studio for the mac, and sql server for mac to start with.

Open the solution, change the appsettings connection to your DB and run it.

**Comment by go2ismail** [comment]
README file already added information how to run the project

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/d41fac38-fe4a-4cd7-a1a9-7267bf927d50)
