### ISSUE TITLE
Where Is Database Files

### ISSUE THREAD

**Issue by chandrabhanchaudhary** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#2]
Sorry To Disturb But Where database file

**Comment by erbhatia** [comment]
Hi,

I too did not find database files. Kindly suggest.

**Comment by winapon** [comment]
Please restore packages in Visual Studio.
Then Migrate the data. It will create the database for you.

**Comment by Rashidmarral** [comment]
Hi,

I too did not find database files. Kindly suggest

**Comment by anupshah2it** [comment]
it does not need database files. EF migration is used which will create the database in (localdb)\\mssqllocaldb

**Comment by Rashidmarral** [comment]
thank you so much for your response....

**Comment by paulliddy** [comment]
Has anyone tried this on a Mac where localdb isn't an option?

**Comment by Rashidmarral** [comment]
No I am just tried on Windows..

**Comment by mansourdxb** [comment]
Hello, I couln't find the db or even found after migration 
Please provide commands

**Comment by vgopinath** [comment]
The DB will be under your username folder.. c:\Users\your_user_name

**Comment by bonlim** [comment]
may i know where is the database ?

**Comment by ayazsayz** [comment]
C:\\Users\Your username folder

**Comment by ayazsayz** [comment]
> may i know where is the database ?
C:\Users\Your username folder

**Comment by sandeepchary2144** [comment]
> > may i know where is the database ?
> > C:\Users\Your username folder

Sir, I checked in the C:\Users\Your username folder but was unable to find the database
could you please tell me what are steps need to follow...
I performed migrations and added tables but those are empty tables unable to login or register.

**Comment by eng-kubra** [comment]
I had the same problem. First of all, install Microsoft SQL server management application on your computer. create a database. Then open the application on visual studio and connect this application with the database you created. it will solve the problem.

**Comment by go2ismail** [comment]
the database will automatically created. just make sure you have correct connection string at appsettings.json
![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/047a00ca-0abc-4997-8359-6ad44d51c4f3)
