### ISSUE TITLE
Need Guidance in running the project

### ISSUE THREAD

**Issue by theumairtahir** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#20]
When I run the project I constantly see the loader and I am unable to add a new record.

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/38358557/a462c949-eca3-498c-b741-31a88f9eef59)

**Comment by go2ismail** [comment]
README file already added information how to run the project

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/3a85a535-b40b-4a47-8051-85287986212f)
