### ISSUE TITLE
Serial Numbers

### ISSUE THREAD

**Issue by ValkyrX** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#22]
Is there any way to log serial numbers of equipment against a customer record and make that  searchable ?

Thanks

**Comment by go2ismail** [comment]
Hi,

You can add string column for the serial number and then show that column at the grid to enable search by that serial number. Example:
![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/dbb2bc69-439e-4c87-a7ef-01e80bd4fe8a)

**Comment by ValkyrX** [comment]
does this allocate against a customers record ? ie who has what serial etc, for example if i have 5 dell monitors can i list all 5 serials and allocate them to a customer when i book out ?

**Comment by go2ismail** [comment]
Hi,

If so, you need to introduce the SN# at the Delivery Order transaction. ex: Customer purchase Five Dell Laptop, so upon Delivery Order to the Customer, there should be Five row with the same Dell Laptop but entered with different SN#.
