### ISSUE TITLE
Workign But

### ISSUE THREAD

**Issue by ValkyrX** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#23]
So i have managed to get the code loaded and running, however its saying i cant delete or edit the default admin in demo mode ? do i need to buy this software or am i missing something, also its got a populated database can i clean that out and start from scratch ?

**Comment by go2ismail** [comment]
Hi,

No need to buy the premium version. Just change the IsDemoVersion from True to False.

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/fc42ea29-4d88-42a7-b45f-6cc78a580a03)
![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/fc53d580-4d67-44d5-85f4-3a62bbf953dd)
