### ISSUE TITLE
Purchase Orders

### ISSUE THREAD

**Issue by ValkyrX** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#24]
Can i edit the Purchase order form so it includes our logo also can we email the PO straight to the suppliers contact email ?

**Comment by go2ismail** [comment]
Yes you can edit all forms and also all other parts of this project code. yes you can sending email in response of any kind of event by injecting your email implementation or injecting existing email service:

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/29c63f78-d9b3-4e18-8260-2c368daa84cd)

**Comment by ValkyrX** [comment]
Thanks for this , so how do I inject the existing code into the po section ? Sorry I'm a newbie with this type of thing

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by go2ismail** [comment]
Hi,

this ref about dependency injection: https://learn.microsoft.com/en-US/aspnet/web-api/overview/advanced/dependency-injection there are a lot more in internet.

below are example how we can inject email service through constructor:

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/edfa6476-4ca7-4511-88b0-e479e42f86c1)

**Comment by ValkyrX** [comment]
Ok i sorted logo , is there anyway to set a custom PO number ?

**Comment by go2ismail** [comment]
Hi,

Custom number sequence features already there. You can customize it to fit your needs.

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/9041cef3-f8a8-47eb-80a4-9d7c3905e38d)

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/e719f039-42db-4099-8f32-feb0b3158023)
