### ISSUE TITLE
Stock Value

### ISSUE THREAD

**Issue by ValkyrX** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#25]
Hi There , not an issue but advice please, how can i get the stock value into the Inventory Stocks ? i have managed to see file InventoryStockList.cshtml and i can see the fields , what table in the database does this page look at as all i can see on the code is 

ViewData["Module"] = "Inventory";

However i cant find anything simply called inventory ? what table / page does this page pull its info from so i can lookup UnitPrice and then howto add a total ie add column stock to unitprice ? 

Thanks
K

**Comment by go2ismail** [comment]
Hi,

Stock come from invenstock odata

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/9d542602-0540-4dea-bf31-53a6a4967053)

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/31633427-47be-4150-b195-2831be29442d)
