### ISSUE TITLE
Purchased Order details adding problem

### ISSUE THREAD

**Issue by yasirkhanmkd** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#3]
Hello,
I want to add details to purchase order but did not able to add, it does not shows any button nor it add automatically on completion. 
Please look into this issue. 

![Untitled](https://user-images.githubusercontent.com/29226446/57574238-c7ceca00-744e-11e9-8b08-48593d8889ad.png)

**Comment by winapon** [comment]
Dear Sir,

There is a save icon in the table as shown in image enclosed image. 
Please press it after you add each product.
To add another product after pressing save, please press '+' icon.

Hope this helps.

![save](https://user-images.githubusercontent.com/11484128/58419151-6d1cab80-80a7-11e9-956b-deb07f009705.jpg)
