### ISSUE TITLE
No Stock checking

### ISSUE THREAD

**Issue by winapon** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#5]
There is now way to check stocks of the products being received. 
Hence no way will know the product quantity available for sale.

Please update the code

**Comment by j-arnott** [comment]
Yes, what good is an inventory management system that does not manage inventory. False advertisement ;)

**Comment by LeeWheeler** [comment]
Also waiting for this as I bought the retail version.

**Comment by go2ismail** [comment]
product stock per WH live demo: https://whms-lte.csharpasp.net/InventoryStocks/InventoryStockList

![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/5a130af4-a10d-4999-afbb-9adaa263001f)
