### ISSUE TITLE
Building in Visual Studio for Mac

### ISSUE THREAD

**Issue by paulliddy** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#6]
Hello, has anyone tried this using Mac? Specifically Visual Studio for Mac? I've encountered this error, which is due to SQL not being native to Mac: "localdb is not supported on this platform". I tried to host SQL inside docker but I couldn't get the 2 connected and the data migrated. 

Thanks!

**Comment by sphola01** [comment]
same here

**Comment by go2ismail** [comment]
please try the newer version, already used .NET 8.0
