### ISSUE TITLE
Upgrading to core 3

### ISSUE THREAD

**Issue by aymangithub** [go2ismail/Asp.Net-Core-Inventory-Order-Management-System#7]
Do you intend to upgrade the project to dotnet core 3 ?

**Comment by krishnamhn009** [comment]
@aymangithub @go2ismail There is pending PR that includes changes for upgrading into .net core 3.1..Please reveiw

**Comment by go2ismail** [comment]
already upgraded to .NET 8.0 
![image](https://github.com/go2ismail/Asp.Net-Core-Inventory-Order-Management-System/assets/2275051/811aa87d-7b7e-446e-8c7e-6c1143247c06)
